STANDART_DATE_YEAR := $(shell date -u +%Y)
STANDART_DATE_MONTH := $(shell date -u +%m)
STANDART_DATE_DAY := $(shell date -u +%d)
STANDART_DATE_HOUR := $(shell date -u +%H)
STANDART_DATE_MINUTE := $(shell date -u +%M)
STANDART_BUILD_DATE_UTC := $(shell date -d '$(STANDART_DATE_YEAR)-$(STANDART_DATE_MONTH)-$(STANDART_DATE_DAY) $(STANDART_DATE_HOUR):$(STANDART_DATE_MINUTE) UTC' +%s)
STANDART_BUILD_DATE := $(STANDART_DATE_YEAR)$(STANDART_DATE_MONTH)$(STANDART_DATE_DAY)-$(STANDART_DATE_HOUR)$(STANDART_DATE_MINUTE)

STANDART_PLATFORM_VERSION := 14.0

STANDART_VERSION := StandartOS_$(STANDART_BUILD)-$(STANDART_PLATFORM_VERSION)-$(STANDART_BUILD_DATE)
STANDART_VERSION_PROP := Fourteen